version: "3.8"

services:
  pgvector:
    image: agnohq/pgvector:16
    container_name: pgvector
    environment:
      - POSTGRES_DB=ai
      - POSTGRES_USER=ai
      - POSTGRES_PASSWORD=ai
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5532:5432"
    volumes:
      - pgvolume:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgvolume:
    driver: local
